name = "beleuchtung-secure-worker"
main = "src/index.js"
compatibility_date = "2026-03-05"

[vars]
ALLOWED_ORIGIN = "https://nero2026.github.io"
ALLOWED_IPS = ""
SHELLY_HOST = "https://shelly-239-eu.shelly.cloud"

DEVICES_JSON = '''
[
  { "key": "test-shelly", "id": "d0cf13cb8708", "channel": 0, "enabled": true },
  { "key": "platzlampe", "id": "28372f2018f8", "channel": 0, "enabled": true },
  { "key": "scheune-vorne", "id": "28372f2018f8", "channel": 1, "enabled": true }
]
'''

SHELLY_DEVICE_ID = ""
